version: '3.8'

services:
  web:
    tty: true
    stdin_open: true
    build:
      context: '.'
      dockerfile: ./docker/Dockerfile
    command: /scripts/entrypoint.sh
    volumes:
      - .:/app
      - ./docker/scripts:/scripts
    ports: ['8080:8080']
